# Generated by Django 3.2.6 on 2021-12-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=45, null=True)),
                ('ogrenci1', models.CharField(blank=True, max_length=45, null=True)),
                ('ogrenci1_no', models.PositiveIntegerField(blank=True, null=True)),
                ('ogrenci2', models.CharField(blank=True, max_length=45, null=True)),
                ('ogrenci2_no', models.PositiveIntegerField(blank=True, null=True)),
                ('ogrenci3', models.CharField(blank=True, max_length=45, null=True)),
                ('ogrenci3_no', models.PositiveIntegerField(blank=True, null=True)),
                ('danisman', models.CharField(blank=True, max_length=45, null=True)),
                ('juri1', models.CharField(blank=True, max_length=45, null=True)),
                ('juri2', models.CharField(blank=True, max_length=45, null=True)),
                ('anahtar', models.CharField(blank=True, max_length=45, null=True)),
                ('ozet', models.CharField(blank=True, max_length=2048, null=True)),
                ('ders_adi', models.CharField(blank=True, max_length=45, null=True)),
                ('donem', models.CharField(blank=True, max_length=45, null=True)),
                ('kullanici', models.PositiveIntegerField(blank=True, null=True)),
                ('tez', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
    ]
