# Generated by Django 3.2.6 on 2021-12-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tez',
            name='anahtar',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
