# Generated by Django 3.2.6 on 2021-12-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezler', '0002_alter_tez_anahtar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tez',
            name='kullanici',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
