# Generated by Django 3.2.6 on 2021-12-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezler', '0003_alter_tez_kullanici'),
    ]

    operations = [
        migrations.AddField(
            model_name='tez',
            name='ogrenci1_ogretim',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='tez',
            name='ogrenci2_ogretim',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='tez',
            name='ogrenci3_ogretim',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
