# Generated by Django 3.2.6 on 2021-12-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezler', '0004_auto_20211220_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tez',
            name='baslik',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
