# Generated by Django 3.2.6 on 2021-12-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezler', '0005_alter_tez_baslik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tez',
            name='baslik',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tez',
            name='ozet',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
