# Generated by Django 3.2.6 on 2021-12-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezler', '0006_auto_20211220_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tez',
            name='ogrenci1_no',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='tez',
            name='ogrenci2_no',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='tez',
            name='ogrenci3_no',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
